# Generated by Django 4.0.4 on 2022-04-17 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0006_remove_answer_modify_date_remove_answer_voter_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='faq',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
