# Generated by Django 4.0.4 on 2022-04-17 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0008_remove_question_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
