# Generated by Django 4.0.4 on 2022-04-17 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0009_question_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='category',
            field=models.CharField(choices=[('general', '일반'), ('account', '계정'), ('etc', '기타')], max_length=8, null=True),
        ),
    ]
